// Prints a model built by model.js as a script for one engine. All decisions
// that can fail (names, types, defaults, keys) were taken in the model; this
// file only knows each engine's grammar and statement separators.

import { DB } from "../../data/constants";
import { DIALECT_NAMES } from "./model";
import { lineComment, stringLiteral } from "./names";

export const INDENT = "  ";

function header(model) {
  if (!model.options.includeHeader) return [];
  const source =
    model.sourceDb === DB.GENERIC ? " (from a generic diagram)" : "";
  return [
    lineComment(
      `Generated by drawDB for ${DIALECT_NAMES[model.dialect]}${source}`,
    ),
  ];
}

export function keyColumns(model, columns) {
  return columns
    .map(
      ({ column, prefix }) =>
        `${model.quote(column.name)}${prefix ? `(${prefix})` : ""}`,
    )
    .join(", ");
}

export function plainColumns(model, columns) {
  return columns.map((column) => model.quote(column.name)).join(", ");
}

export function constraintPrefix(model, name) {
  return name ? `CONSTRAINT ${model.quote(name)} ` : "";
}

export function foreignKeyClause(model, fk, { ifNotExists = false } = {}) {
  const actions = [
    fk.onDelete ? ` ON DELETE ${fk.onDelete}` : "",
    fk.onUpdate ? ` ON UPDATE ${fk.onUpdate}` : "",
  ].join("");
  return `${constraintPrefix(model, fk.name)}FOREIGN KEY ${ifNotExists ? "IF NOT EXISTS " : ""}(${plainColumns(model, fk.columns)}) REFERENCES ${fk.parent.sql} (${plainColumns(model, fk.refColumns)})${actions}`;
}

// Unnamed checks stay on their column; named ones are table constraints.
function checks(column) {
  return column.checks
    .filter((check) => !check.name)
    .map((check) => ` CHECK (${check.expr})`)
    .join("");
}

export function checkClause(model, check) {
  return `${constraintPrefix(model, check.name)}CHECK (${check.expr})`;
}

function namedChecks(model, table) {
  return table.columns.flatMap((column) =>
    column.checks
      .filter((check) => check.name)
      .map((check) => checkClause(model, check)),
  );
}

export function truncateComment(model, text, max, object) {
  if (text.length <= max) return text;
  model.issues.push({
    level: "warning",
    code: "comment_truncated",
    params: { object, max, dialect: DIALECT_NAMES[model.dialect] },
  });
  return text.slice(0, max);
}

/** Lines inside CREATE TABLE ( ... ) that come after the columns. */
function tableConstraints(model, table, { prefixKeys = false } = {}) {
  const lines = namedChecks(model, table);
  if (table.primaryKey) {
    lines.push(
      `${constraintPrefix(model, table.primaryKey.name)}PRIMARY KEY (${
        prefixKeys
          ? keyColumns(model, table.primaryKey.columns)
          : plainColumns(
              model,
              table.primaryKey.columns.map((c) => c.column),
            )
      })`,
    );
  }
  for (const unique of table.uniques) {
    lines.push(
      `${constraintPrefix(model, unique.name)}UNIQUE (${
        prefixKeys
          ? keyColumns(model, unique.columns)
          : plainColumns(
              model,
              unique.columns.map((c) => c.column),
            )
      })`,
    );
  }
  return lines;
}

function inlineForeignKeys(model, table) {
  return table.foreignKeys
    .filter((fk) => fk.placement === "inline")
    .map((fk) => foreignKeyClause(model, fk));
}

function alterForeignKeys(model) {
  return model.foreignKeys.filter((fk) => fk.placement === "alter");
}

function createTableBody(lines) {
  return lines.map((line) => `${INDENT}${line}`).join(",\n");
}

// --- MySQL and MariaDB ----------------------------------------------------------

function mysqlColumn(model, table, column, { identity = true } = {}) {
  const { options, quote, literal } = model;
  let line = `${quote(column.name)} ${column.sql}`;
  if (column.unsigned) line += " UNSIGNED";
  if (column.notNull) line += " NOT NULL";
  if (column.defaultSql !== null) line += ` DEFAULT ${column.defaultSql}`;
  if (column.identity && identity) line += " AUTO_INCREMENT";
  if (options.includeComments && column.comment.trim()) {
    const text = truncateComment(
      model,
      column.comment,
      1024,
      `${table.name}.${column.name}`,
    );
    line += ` COMMENT ${literal(text)}`;
  }
  return line;
}

function renderMySQL(model) {
  const { options, quote, literal } = model;
  const out = [...header(model)];
  const ifNotExists =
    options.existing === "if_not_exists" ? "IF NOT EXISTS " : "";
  const needsChecksOff =
    options.existing === "drop_create" ||
    model.foreignKeys.some((fk) => fk.placement === "inline");

  if (model.schema && options.createSchema) {
    out.push(`CREATE DATABASE IF NOT EXISTS ${quote(model.schema)};`);
  }
  if (needsChecksOff) out.push("SET FOREIGN_KEY_CHECKS = 0;");
  if (options.existing === "drop_create" && model.tables.length) {
    out.push(
      `DROP TABLE IF EXISTS ${model.tables.map((t) => t.sql).join(", ")};`,
    );
  }

  for (const table of model.tables) {
    const lines = table.columns.map(
      (column) => mysqlColumn(model, table, column) + checks(column),
    );
    lines.push(...tableConstraints(model, table, { prefixKeys: true }));
    for (const index of table.indexes) {
      lines.push(
        `${index.unique ? "UNIQUE " : ""}INDEX ${quote(index.name)} (${keyColumns(model, index.columns)})`,
      );
    }
    lines.push(...inlineForeignKeys(model, table));

    const tableOptions = [];
    if (options.mysqlEngine) tableOptions.push(`ENGINE=${options.mysqlEngine}`);
    if (options.mysqlCharset)
      tableOptions.push(`DEFAULT CHARSET=${options.mysqlCharset}`);
    if (options.mysqlCollation)
      tableOptions.push(`COLLATE=${options.mysqlCollation}`);
    if (options.includeComments && table.comment.trim()) {
      const text = truncateComment(model, table.comment, 2048, table.name);
      tableOptions.push(`COMMENT=${literal(text)}`);
    }
    out.push(
      `CREATE TABLE ${ifNotExists}${table.sql} (\n${createTableBody(lines)}\n)${tableOptions.length ? ` ${tableOptions.join(" ")}` : ""};`,
    );
  }

  const guard = options.existing === "if_not_exists";
  for (const fk of alterForeignKeys(model)) {
    if (guard && fk.name && model.dialect === DB.MARIADB) {
      out.push(
        `ALTER TABLE ${fk.child.sql} ADD ${foreignKeyClause(model, fk, { ifNotExists: true })};`,
      );
    } else if (guard && fk.name) {
      // MySQL has no IF NOT EXISTS for constraints: look the name up first.
      const statement = `ALTER TABLE ${fk.child.sql} ADD ${foreignKeyClause(model, fk)}`;
      const schema = model.schema ? literal(model.schema) : "DATABASE()";
      out.push(
        [
          `SET @drawdb_ddl = IF((SELECT COUNT(*) FROM information_schema.TABLE_CONSTRAINTS WHERE CONSTRAINT_SCHEMA = ${schema} AND TABLE_NAME = ${literal(fk.child.name)} AND CONSTRAINT_NAME = ${literal(fk.name)} AND CONSTRAINT_TYPE = 'FOREIGN KEY') = 0, ${literal(statement)}, 'DO 0');`,
          "PREPARE drawdb_stmt FROM @drawdb_ddl;",
          "EXECUTE drawdb_stmt;",
          "DEALLOCATE PREPARE drawdb_stmt;",
        ].join("\n"),
      );
    } else {
      out.push(
        `ALTER TABLE ${fk.child.sql} ADD ${foreignKeyClause(model, fk)};`,
      );
    }
  }
  if (needsChecksOff) out.push("SET FOREIGN_KEY_CHECKS = 1;");
  return out.join("\n\n");
}

// --- PostgreSQL ------------------------------------------------------------------

export function pgGuard(statement) {
  // Runs `statement` and ignores "already exists", so the script can re-run.
  const tag = statement.includes("$drawdb$") ? "$drawdb_ddl$" : "$drawdb$";
  return `DO ${tag}\nBEGIN\n${INDENT}${statement.replace(/\n/g, `\n${INDENT}`)}\nEXCEPTION\n${INDENT}WHEN duplicate_object THEN NULL;\nEND ${tag};`;
}

export function identityClause(model) {
  return `GENERATED ${model.options.identityGeneration === "always" ? "ALWAYS" : "BY DEFAULT"} AS IDENTITY`;
}

function postgresColumn(model, column) {
  let line = `${model.quote(column.name)} ${column.sql}`;
  if (column.identity && !column.serial) line += ` ${identityClause(model)}`;
  if (column.notNull) line += " NOT NULL";
  if (column.defaultSql !== null) line += ` DEFAULT ${column.defaultSql}`;
  return line;
}

function renderPostgres(model) {
  const { options, quote, literal, qualify } = model;
  const out = [...header(model)];
  const guard = options.existing === "if_not_exists";
  const ifNotExists = guard ? "IF NOT EXISTS " : "";

  if (options.wrapInTransaction) out.push("BEGIN;");
  if (model.schema && options.createSchema) {
    out.push(`CREATE SCHEMA IF NOT EXISTS ${quote(model.schema)};`);
  }
  if (options.pgCreateExtensions) {
    for (const extension of model.extensions) {
      out.push(`CREATE EXTENSION IF NOT EXISTS ${quote(extension)};`);
    }
  }
  if (options.existing === "drop_create") {
    for (const table of [...model.tables].reverse()) {
      out.push(`DROP TABLE IF EXISTS ${table.sql} CASCADE;`);
    }
    for (const type of [...model.compositeTypes].reverse()) {
      out.push(`DROP TYPE IF EXISTS ${qualify(type.name)} CASCADE;`);
    }
    for (const entry of model.enums) {
      out.push(`DROP TYPE IF EXISTS ${qualify(entry.name)} CASCADE;`);
    }
  }

  const typeStatement = (statement) => (guard ? pgGuard(statement) : statement);
  for (const entry of model.enums) {
    out.push(
      typeStatement(
        `CREATE TYPE ${qualify(entry.name)} AS ENUM (${entry.values.map(literal).join(", ")});`,
      ),
    );
  }
  for (const type of model.compositeTypes) {
    const fields = type.fields
      .map((field) => `${INDENT}${quote(field.name)} ${field.sql}`)
      .join(",\n");
    out.push(
      typeStatement(`CREATE TYPE ${qualify(type.name)} AS (\n${fields}\n);`),
    );
    if (options.includeComments && type.comment.trim()) {
      out.push(
        `COMMENT ON TYPE ${qualify(type.name)} IS ${literal(type.comment)};`,
      );
    }
  }

  for (const table of model.tables) {
    const lines = table.columns.map(
      (column) => postgresColumn(model, column) + checks(column),
    );
    lines.push(...tableConstraints(model, table));
    lines.push(...inlineForeignKeys(model, table));
    const inherits = table.inherits.length
      ? ` INHERITS (${table.inherits.map((name) => qualify(name)).join(", ")})`
      : "";
    out.push(
      `CREATE TABLE ${ifNotExists}${table.sql} (\n${createTableBody(lines)}\n)${inherits};`,
    );

    if (options.includeComments) {
      if (table.comment.trim()) {
        out.push(`COMMENT ON TABLE ${table.sql} IS ${literal(table.comment)};`);
      }
      for (const column of table.columns) {
        if (!column.comment.trim()) continue;
        out.push(
          `COMMENT ON COLUMN ${table.sql}.${quote(column.name)} IS ${literal(column.comment)};`,
        );
      }
    }
    for (const index of table.indexes) {
      out.push(
        `CREATE ${index.unique ? "UNIQUE " : ""}INDEX ${ifNotExists}${quote(index.name)} ON ${table.sql} (${plainColumns(
          model,
          index.columns.map((c) => c.column),
        )});`,
      );
    }
  }

  for (const fk of alterForeignKeys(model)) {
    const statement = `ALTER TABLE ${fk.child.sql} ADD ${foreignKeyClause(model, fk)};`;
    out.push(guard ? pgGuard(statement) : statement);
  }
  if (options.wrapInTransaction) out.push("COMMIT;");
  return out.join("\n\n");
}

// --- SQLite ------------------------------------------------------------------------

function sqliteColumn(model, column) {
  let line = `${model.quote(column.name)} ${column.sql}`;
  if (column.sqliteRowid) {
    line += " PRIMARY KEY";
    if (model.options.sqliteAutoincrement) line += " AUTOINCREMENT";
  }
  if (column.notNull) line += " NOT NULL";
  if (column.defaultSql !== null) line += ` DEFAULT ${column.defaultSql}`;
  return line;
}

function renderSQLite(model) {
  const { options, quote } = model;
  const out = [...header(model)];
  const ifNotExists =
    options.existing === "if_not_exists" ? "IF NOT EXISTS " : "";
  const drop = options.existing === "drop_create";

  // PRAGMA foreign_keys does nothing inside a transaction, so it goes outside.
  if (drop) out.push("PRAGMA foreign_keys = OFF;");
  else if (options.sqliteForeignKeysPragma)
    out.push("PRAGMA foreign_keys = ON;");
  if (options.wrapInTransaction) out.push("BEGIN TRANSACTION;");
  if (drop) {
    for (const table of [...model.tables].reverse()) {
      out.push(`DROP TABLE IF EXISTS ${table.sql};`);
    }
  }

  for (const table of model.tables) {
    const lines = table.columns.map((column) => {
      const comment =
        options.includeComments && column.comment.trim()
          ? `${lineComment(column.comment)}\n${INDENT}`
          : "";
      return comment + sqliteColumn(model, column) + checks(column);
    });
    lines.push(...tableConstraints(model, table));
    lines.push(...inlineForeignKeys(model, table));
    const comment =
      options.includeComments && table.comment.trim()
        ? `${lineComment(table.comment)}\n`
        : "";
    out.push(
      `${comment}CREATE TABLE ${ifNotExists}${table.sql} (\n${createTableBody(lines)}\n);`,
    );
    for (const index of table.indexes) {
      out.push(
        `CREATE ${index.unique ? "UNIQUE " : ""}INDEX ${ifNotExists}${quote(index.name)} ON ${table.sql} (${plainColumns(
          model,
          index.columns.map((c) => c.column),
        )});`,
      );
    }
  }

  if (options.wrapInTransaction) out.push("COMMIT;");
  if (drop && options.sqliteForeignKeysPragma) {
    out.push("PRAGMA foreign_keys = ON;");
  }
  return out.join("\n\n");
}

// --- SQL Server ------------------------------------------------------------------------

function mssqlColumn(model, column, { withDefault = true } = {}) {
  const { quote } = model;
  let line = `${quote(column.name)} ${column.sql}`;
  if (column.defaultSql !== null && withDefault) {
    const name = column.defaultName
      ? `CONSTRAINT ${quote(column.defaultName)} `
      : "";
    line += ` ${name}DEFAULT ${column.defaultSql}`;
  }
  if (column.identity) line += " IDENTITY(1,1)";
  line += column.notNull ? " NOT NULL" : " NULL";
  return line;
}

function renderMSSQL(model) {
  const { options, quote, literal, qualify } = model;
  const go = options.mssqlBatchSeparator;
  const guard = options.existing === "if_not_exists";
  const batches = [];
  const batch = (text) => batches.push(text);
  const nameText = (name) => stringLiteral(qualify(name), DB.MSSQL);
  const objectId = (table, type) =>
    `OBJECT_ID(${stringLiteral(table.sql, DB.MSSQL)}${type ? `, N'${type}'` : ""})`;
  const schemaLiteral = model.schema
    ? stringLiteral(model.schema, DB.MSSQL)
    : "@schema";

  if (options.wrapInTransaction) {
    batch("SET XACT_ABORT ON;\nBEGIN TRANSACTION;");
  }
  if (model.schema && options.createSchema) {
    batch(
      `IF SCHEMA_ID(${stringLiteral(model.schema, DB.MSSQL)}) IS NULL\n${INDENT}EXEC(${stringLiteral(`CREATE SCHEMA ${quote(model.schema)}`, DB.MSSQL)});`,
    );
  }
  if (options.existing === "drop_create" && model.tables.length) {
    const ids = model.tables.map((t) => objectId(t)).join(", ");
    batch(
      [
        "DECLARE @drop NVARCHAR(MAX) = N'';",
        "SELECT @drop += N'ALTER TABLE ' + QUOTENAME(OBJECT_SCHEMA_NAME(parent_object_id)) + N'.' + QUOTENAME(OBJECT_NAME(parent_object_id)) + N' DROP CONSTRAINT ' + QUOTENAME(name) + N';'",
        `FROM sys.foreign_keys WHERE referenced_object_id IN (${ids});`,
        "EXEC sp_executesql @drop;",
      ].join("\n"),
    );
    for (const table of [...model.tables].reverse()) {
      batch(
        `IF ${objectId(table, "U")} IS NOT NULL\n${INDENT}DROP TABLE ${table.sql};`,
      );
    }
  }

  let declaredSchema = false;
  const describe = (table, column, text) => {
    const target = column
      ? `, @level2type = N'COLUMN', @level2name = ${stringLiteral(column.name, DB.MSSQL)}`
      : "";
    const exec = `EXEC sys.sp_addextendedproperty @name = N'MS_Description', @value = ${literal(text)}, @level0type = N'SCHEMA', @level0name = ${schemaLiteral}, @level1type = N'TABLE', @level1name = ${stringLiteral(table.name, DB.MSSQL)}${target};`;
    if (!guard) return exec;
    const minor = column
      ? `COLUMNPROPERTY(${objectId(table)}, ${stringLiteral(column.name, DB.MSSQL)}, 'ColumnId')`
      : "0";
    return `IF NOT EXISTS (SELECT 1 FROM sys.extended_properties WHERE major_id = ${objectId(table)} AND minor_id = ${minor} AND name = N'MS_Description')\n${INDENT}${exec}`;
  };

  for (const table of model.tables) {
    const lines = table.columns.map(
      (column) => mssqlColumn(model, column) + checks(column),
    );
    lines.push(...tableConstraints(model, table));
    lines.push(...inlineForeignKeys(model, table));
    const create = `CREATE TABLE ${table.sql} (\n${createTableBody(lines)}\n);`;
    batch(guard ? `IF ${objectId(table, "U")} IS NULL\n${create}` : create);

    if (options.includeComments) {
      const statements = [];
      if (table.comment.trim())
        statements.push(describe(table, null, table.comment));
      for (const column of table.columns) {
        if (column.comment.trim())
          statements.push(describe(table, column, column.comment));
      }
      if (statements.length) {
        const declare =
          !model.schema && (go || !declaredSchema)
            ? "DECLARE @schema sysname = SCHEMA_NAME();\n"
            : "";
        declaredSchema = true;
        batch(declare + statements.join("\n"));
      }
    }
    for (const index of table.indexes) {
      const create = `CREATE ${index.unique ? "UNIQUE " : ""}INDEX ${quote(index.name)} ON ${table.sql} (${plainColumns(
        model,
        index.columns.map((c) => c.column),
      )});`;
      batch(
        guard
          ? `IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = ${stringLiteral(index.name, DB.MSSQL)} AND object_id = ${objectId(table)})\n${INDENT}${create}`
          : create,
      );
    }
  }

  for (const fk of alterForeignKeys(model)) {
    const statement = `ALTER TABLE ${fk.child.sql} ADD ${foreignKeyClause(model, fk)};`;
    batch(
      guard && fk.name
        ? `IF OBJECT_ID(${nameText(fk.name)}, N'F') IS NULL\n${INDENT}${statement}`
        : statement,
    );
  }
  if (options.wrapInTransaction) batch("COMMIT TRANSACTION;");

  const out = [...header(model)];
  for (const text of batches) out.push(go ? `${text}\nGO` : text);
  return out.join("\n\n");
}

// --- Oracle ------------------------------------------------------------------------------

export function oracleBlock(statement, ignoredCodes) {
  const ddl = statement.replace(/;\s*$/, "");
  const condition =
    ignoredCodes.length === 1
      ? `SQLCODE != ${ignoredCodes[0]}`
      : `SQLCODE NOT IN (${ignoredCodes.join(", ")})`;
  return [
    "BEGIN",
    `${INDENT}EXECUTE IMMEDIATE ${stringLiteral(ddl, DB.ORACLESQL)};`,
    "EXCEPTION",
    `${INDENT}WHEN OTHERS THEN`,
    `${INDENT}${INDENT}IF ${condition} THEN`,
    `${INDENT}${INDENT}${INDENT}RAISE;`,
    `${INDENT}${INDENT}END IF;`,
    "END;",
    "/",
  ].join("\n");
}

// ORA-00955 name in use, ORA-02260/02261 key exists, ORA-02275 FK exists,
// ORA-01408 column list already indexed.
const ORACLE_EXISTS = [-955, -2260, -2261, -2275, -1408];

function oracleColumn(model, column) {
  let line = `${model.quote(column.name)} ${column.sql}`;
  if (column.identity) line += ` ${identityClause(model)}`;
  else if (column.defaultSql !== null) line += ` DEFAULT ${column.defaultSql}`;
  if (column.notNull) line += " NOT NULL";
  return line;
}

function renderOracle(model) {
  const { options, quote, literal, qualify } = model;
  const out = [...header(model)];
  const guard = options.existing === "if_not_exists";
  const ddl = (statement) =>
    guard ? oracleBlock(statement, ORACLE_EXISTS) : statement;

  if (options.existing === "drop_create") {
    for (const table of [...model.tables].reverse()) {
      out.push(
        oracleBlock(`DROP TABLE ${table.sql} CASCADE CONSTRAINTS PURGE`, [
          -942,
        ]),
      );
    }
  }

  for (const table of model.tables) {
    const lines = table.columns.map(
      (column) => oracleColumn(model, column) + checks(column),
    );
    lines.push(...tableConstraints(model, table));
    lines.push(...inlineForeignKeys(model, table));
    out.push(ddl(`CREATE TABLE ${table.sql} (\n${createTableBody(lines)}\n);`));

    if (options.includeComments) {
      if (table.comment.trim()) {
        const text = truncateComment(model, table.comment, 4000, table.name);
        out.push(`COMMENT ON TABLE ${table.sql} IS ${literal(text)};`);
      }
      for (const column of table.columns) {
        if (!column.comment.trim()) continue;
        const text = truncateComment(
          model,
          column.comment,
          4000,
          `${table.name}.${column.name}`,
        );
        out.push(
          `COMMENT ON COLUMN ${table.sql}.${quote(column.name)} IS ${literal(text)};`,
        );
      }
    }
    for (const index of table.indexes) {
      out.push(
        ddl(
          `CREATE ${index.unique ? "UNIQUE " : ""}INDEX ${qualify(index.name)} ON ${table.sql} (${plainColumns(
            model,
            index.columns.map((c) => c.column),
          )});`,
        ),
      );
    }
  }

  for (const fk of alterForeignKeys(model)) {
    out.push(
      ddl(`ALTER TABLE ${fk.child.sql} ADD ${foreignKeyClause(model, fk)};`),
    );
  }
  return out.join("\n\n");
}

/**
 * One column as CREATE TABLE or ALTER TABLE ... ADD prints it, without its
 * checks. `identity: false` leaves out MySQL's AUTO_INCREMENT and
 * `withDefault: false` SQL Server's default constraint.
 */
export function columnDefinition(model, table, column, flags = {}) {
  switch (model.dialect) {
    case DB.MYSQL:
    case DB.MARIADB:
      return mysqlColumn(model, table, column, flags);
    case DB.POSTGRES:
      return postgresColumn(model, column);
    case DB.SQLITE:
      return sqliteColumn(model, column);
    case DB.MSSQL:
      return mssqlColumn(model, column, flags);
    case DB.ORACLESQL:
      return oracleColumn(model, column);
    default:
      return "";
  }
}

export function renderModel(model) {
  switch (model.dialect) {
    case DB.MYSQL:
    case DB.MARIADB:
      return renderMySQL(model);
    case DB.POSTGRES:
      return renderPostgres(model);
    case DB.SQLITE:
      return renderSQLite(model);
    case DB.MSSQL:
      return renderMSSQL(model);
    case DB.ORACLESQL:
      return renderOracle(model);
    default:
      return "";
  }
}
